name: thesis_opacus
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flake8
  - pip:
    - torch==2.0
    - torchvision
    - torchaudio
    - einops
    - pandas
    - kaggle
    - wandb
    - torchmetrics==1.0.3
    - nibabel
    - scikit-learn
    - h5py
    - pydicom
    - tqdm
    - matplotlib
    #- opacus==1.4.0
    - dotmap
    - tensorboard