name: thesis_custom_opacus
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flake8
  - pip:
    - torch==2.0
    #- torch==1.13.1
    - torchvision
    #- torchvision==0.14.1
    - torchaudio
    #- torchaudio==0.13.1
    - einops
    - pandas
    - kaggle
    - wandb
    - torchmetrics==0.11.4
    - nibabel
    - scikit-learn
    - h5py
    - pydicom
    - tqdm
    - matplotlib
    #- opacus
    - dotmap
    - tensorboard
