name: thesis
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - flake8
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - torchaudio==0.13.1
    - einops
    - pandas
    - kaggle
    - wandb
    - torchmetrics
    - nibabel
    - scikit-learn
    - h5py
    - pydicom
    - tqdm
    - matplotlib
    - opacus
    - dotmap
    - tensorboard
