---
run1:
  protected_attr: "age"
  protected_attr_percent: [0,1,0.25]
  num_seeds: 3
  wandb_project: "unsupervised-fairness"
  max_steps: 100000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"