#!/bin/bash
#SBATCH --partition=master
#SBATCH --ntasks=1
#SBATCH --time=07-00:00:00
#SBATCH --mem=32G
#SBATCH --gres=gpu:1

# Load the Anaconda module
module load python/anaconda3

# Specify the Anaconda environment name
ANACONDA_ENV="thesis_opacus"

# Specify the full path to the Anaconda environment's Python interpreter
ANACONDA_PYTHON="/u/home/getzner/.conda/envs/$ANACONDA_ENV/bin/python"

# Activate the Anaconda environment
source activate $ANACONDA_ENV

# Your commands using the Anaconda environment
echo "Running script with Anaconda environment: $ANACONDA_ENV"

date=$(date '+%Y-%m-%d %H:%M:%S')
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.1 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.2 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.9	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.8	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.7	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.6	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.5	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.4	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.3	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.2	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.1	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.25 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.3 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.4 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.5 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.6 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.7 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.9	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.8	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.7	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.6	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.5	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.4	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.3	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.2	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.1	  --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.75 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.8 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v1 --protected_attr_percent 0.9 --loss_weight_type "old_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

# --------------
# SEX
# --------------
date=$(date '+%Y-%m-%d %H:%M:%S')
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.10 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.20 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.25 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.30 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.40 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.50 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.60 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.70 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.75 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.001	  --group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.80 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"

$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.9	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-09" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.8	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-08" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.7	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-07" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.6	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-06" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.5	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-05" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.4	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-04" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.3	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-03" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.2	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-02" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.1	    --group_name_mod "bs32-lossweight"    --job_type_mod "oldweight-01" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.001 	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-001" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.0005	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0005" --d "${date}"
$ANACONDA_PYTHON -u train.py --run_config normal --run_version v2 --protected_attr_percent 0.90 --loss_weight_type "male_weight" --weight 0.0001	--group_name_mod "bs32-lossweight"  --job_type_mod "oldweight-0001" --d "${date}"