---
# default age
v1:
  dp: False
  protected_attr: "age"
  initial_seed: 1
  num_seeds: 5
  wandb_project: "unsupervised-fairness"
  num_steps: 8000
  batch_size: 32
v1_dataset_distill:
  dp: False
  protected_attr: "age"
  initial_seed: 1
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  num_steps: 3000
  batch_size: 32
# default sex
v2:
  dp: False
  protected_attr: "sex"
  initial_seed: 1
  num_seeds: 5
  wandb_project: "unsupervised-fairness"
  num_steps: 8000
  batch_size: 32
balanced_baseline:
  dp: False
  protected_attr: "balanced"
  initial_seed: 1
  num_seeds: 10
  wandb_project: "unsupervised-fairness"
  num_steps: 10000
  batch_size: 32
distill_baseline:
  dp: False
  protected_attr: "balanced"
  initial_seed: 1
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  num_steps: 3000
  batch_size: 32