---
run3:
  protected_attr: "sex"
  protected_attr_percent: 0.5
  num_seeds: 3
  wandb_project: "unsupervised-fairness"
  max_steps: 20000
  dp: True
  batch_size: 256
  max_grad_norm: 0.01
  job_type_mod: "bs256_mgn001"
run4:
  protected_attr: "sex"
  protected_attr_percent: 0.5
  num_seeds: 3
  wandb_project: "unsupervised-fairness"
  max_steps: 20000
  dp: True
  batch_size: 512
  max_grad_norm: 0.01
  job_type_mod: "bs512_mgn001"
