---
run1:
  protected_attr: "sex"
  protected_attr_percent: 0.5
  num_seeds: 2
  wandb_project: "unsupervised-fairness"
  max_steps: 35000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.015
  job_type_mod: "bs1024_mgn0015"
