---
# default age
v1:
  dp: True
  max_grad_norm: 0.01
  protected_attr: "age"
  initial_seed: 1
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  epochs: 15000
  batch_size: 1024
  max_physical_batch_size: 256
  lr: 0.0002

# default sex
v2:
  dp: True
  max_grad_norm: 0.01
  protected_attr: "sex"
  initial_seed: 1
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  epochs: 7500
  batch_size: 512
  max_physical_batch_size: 512
  lr: 0.0002
