---
# default age
v1:
  dp: False
  protected_attr: "age"
  initial_seed: 1
  num_seeds: 5
  wandb_project: "unsupervised-fairness"
  epochs: 8000
  batch_size: 32
# default sex
v2:
  dp: False
  protected_attr: "sex"
  initial_seed: 1
  num_seeds: 5
  wandb_project: "unsupervised-fairness"
  epochs: 67
  batch_size: 32