---
dp_1:
  protected_attr: "age"
  protected_attr_percent: [0.5,1,0.25]
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  max_steps: 50000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 512
dp_2:
  protected_attr: "age"
  protected_attr_percent: [0,0.5,0.25]
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  max_steps: 50000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 512
  initial_seed: 100
no_dp_age:
  protected_attr: "age"
  protected_attr_percent: [0,1,0.25]
  num_seeds: 10
  wandb_project: "unsupervised-fairness"
  max_steps: 8000
  dp: False
  batch_size: 32
  group_name_mod: "bs32"
  max_physical_batch_size: 32
no_dp_sex:
  protected_attr: "sex"
  protected_attr_percent: [0,1,0.1]
  num_seeds: 10
  wandb_project: "unsupervised-fairness"
  max_steps: 8000
  dp: False
  batch_size: 32
  group_name_mod: "bs32"
  max_physical_batch_size: 32
