---
run1:
  protected_attr: "age"
  protected_attr_percent: [0,1,0.25]
  num_seeds: 2
  wandb_project: "test"
  max_steps: 500
  dp: True
  batch_size: 8
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 8