---
dp_1:
  protected_attr: "age"
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  max_steps: 50000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 512
  initial_seed: 101
dp_2:
  protected_attr: "age"
  num_seeds: 1
  wandb_project: "unsupervised-fairness"
  max_steps: 50000
  dp: True
  batch_size: 1024
  max_grad_norm: 0.01
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 512
  initial_seed: 110
test_local:
  protected_attr: "age"
  num_seeds: 1
  wandb_project: "test"
  max_steps: 300
  dp: True
  batch_size: 32
  group_name_mod: "b32"
  max_physical_batch_size: 32
test_cluster:
  protected_attr: "sex"
  num_seeds: 2
  wandb_project: "age"
  max_steps: 1500
  dp: True
  batch_size: 1024
  group_name_mod: "bs1024_mgn001"
  max_physical_batch_size: 512