---
experiment_config:
  dp: True
  initial_seed: 1
  epochs: 7500
  batch_size: 1024
  max_physical_batch_size: 256
  max_grad_norm: 0.01
  protected_attr: "age"
  wandb_project: "unsupervised-fairness"

sweep_config:
  method: 'grid'
  parameters:
    lr:
      values: [0.001, 0.0009, 0.0007, 0.0005, 0.0003, 0.0001]
  metric:
    goal: 'minimize'
    name: "train/loss"