---
experiment_config:
  dp: True
  # initial_seed: 1
  # num_seeds: 1
  epochs: 3
  batch_size: 32
  max_grad_norm: 0.01
  max_physical_batch_size: 16
  protected_attr: "age"
  wandb_project: "test"
  group_name_mod: "SWEEP_lr_bs1024_mgn001_old_down_weighted"
  # weigh_loss: "old_down_weighted"
  # n_adam: False
sweep_config:
  method: 'random'
  parameters:
    lr:
      max: 0.01
      min: 0.001
  metric:
    goal: 'minimize'
    name: "train/loss"
