---
run1:
  exp_config:
    num_runs: 50
    protected_attr: "sex"
    experiment_name: "FAE-rsna-sweep-maxgradnorm-001-0001"
    max_steps: 6000
    dp: True
  sweep_config:
    method: 'random'
    parameters:
      max_grad_norm:
        max: 0.01
        min: 0.001
    metric:
      goal: 'minimize'
      name: "train/loss"