---
exp_config:
  num_runs: 50
  protected_attr: "sex"
  max_steps: 20000
  dp: True
  wandb_project: "unsupervised-fairness"
  sweep_param: "max_grad_norm"
sweep_config:
  method: 'random'
  parameters:
    max_grad_norm:
      max: 0.01
      min: 0.001
  metric:
    goal: 'minimize'
    name: "train/loss"
